  CREATE TABLE "ESSAYS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TITLE" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"FILE_BLOB" BLOB, 
	"FILE_NAME" VARCHAR2(255 CHAR), 
	"MIME_TYPE" VARCHAR2(255 CHAR), 
	"FILE_DATE" DATE, 
	"CREATED" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED" DATE, 
	"UPDATED_BY" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"YEAR" NUMBER NOT NULL ENABLE, 
	"MONTH" NUMBER, 
	 CONSTRAINT "ESSAYS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USER_MESSAGES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CONV_ID" NUMBER NOT NULL ENABLE, 
	"SEND_TO" NUMBER NOT NULL ENABLE, 
	"SEND_FROM" NUMBER NOT NULL ENABLE, 
	"IS_READ" NUMBER, 
	"SEND_DATE" DATE, 
	"TEXT" VARCHAR2(4000), 
	"FILE_NAME" VARCHAR2(255), 
	"MIME_TYPE" VARCHAR2(255), 
	"FILE_BLOB" BLOB, 
	"CREATED" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED" DATE, 
	"UPDATED_BY" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CODE_LIST" 
   (	"CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"CREATED" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED" DATE, 
	"UPDATED_BY" NUMBER, 
	 PRIMARY KEY ("CODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CODE_LIST_VALUES" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CL_CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"UCODE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"CREATED" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED" DATE, 
	"UPDATED_BY" NUMBER, 
	"CL_CODE4NEXT" VARCHAR2(100), 
	 CONSTRAINT "CODE_LIST_VALUES_UNIQUE" UNIQUE ("UCODE")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USERS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"AM" VARCHAR2(50 CHAR), 
	"ROLE_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"TYPE_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CREATED" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED" DATE, 
	"UPDATED_BY" NUMBER, 
	"ACTIVE" NUMBER NOT NULL ENABLE, 
	"ISADMIN" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USER_CONVERSATIONS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"SEND_FROM" NUMBER NOT NULL ENABLE, 
	"SEND_TO" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE, 
	"IS_CLOSED" NUMBER, 
	"CREATED_BY" NUMBER, 
	"UPDATED" DATE, 
	"UPDATED_BY" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USER_CREDENTIALS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED" DATE, 
	"UPDATED_BY" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "USER_CREDENTIALS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "USER_CREDENTIALS_UN" UNIQUE ("USERNAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USER_DETAILS" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(100 CHAR), 
	"ADDRESS" VARCHAR2(1000 CHAR), 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"UNIVERSITY_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DEPARTMENT_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"STUDY_YEAR" VARCHAR2(20), 
	"CREATED" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED" DATE, 
	"UPDATED_BY" NUMBER, 
	 CONSTRAINT "USER_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "USER_DETAILS_UN" UNIQUE ("EMAIL")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "VERIFICATION_CODE" 
   (	"ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CODE" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE, 
	 CONSTRAINT "VERIFICATION_CODE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

   COMMENT ON COLUMN "CODE_LIST"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "CODE_LIST"."DESCRIPTION" IS 'Περιγραφή';
   COMMENT ON COLUMN "CODE_LIST"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "CODE_LIST"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "CODE_LIST"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "CODE_LIST"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CL" 
before
insert or update on "CODE_LIST"
for each row
begin
    IF INSERTING THEN
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID'); 
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_CL" ENABLE;

  ALTER TABLE "CODE_LIST_VALUES" ADD CONSTRAINT "CLV_FK" FOREIGN KEY ("CL_CODE")
	  REFERENCES "CODE_LIST" ("CODE") ENABLE;

   COMMENT ON COLUMN "CODE_LIST_VALUES"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CL_CODE" IS 'ID Code List';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UCODE" IS 'Κωδικός Εγγραφής';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."DESCRIPTION" IS 'Περιγραφή';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CLV" 
before insert or update on "CODE_LIST_VALUES"
for each row
begin
    IF INSERTING THEN
    if :new.id is null then
        select seq_clv.nextval into :new.id from dual;
    end if;
    :new.ucode := :new.cl_code||':'||:new.code;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID');  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_CLV" ENABLE;

  ALTER TABLE "ESSAYS" ADD CONSTRAINT "ESSAYS_CON" FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("ID") ENABLE;

   COMMENT ON COLUMN "ESSAYS"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "ESSAYS"."TITLE" IS 'Τίτλος πτυχιακής';
   COMMENT ON COLUMN "ESSAYS"."DESCRIPTION" IS 'Περιγραφή θέματος πτυχιακής';
   COMMENT ON COLUMN "ESSAYS"."FILE_BLOB" IS 'Αρχείο αναλυτικής περιγραφής';
   COMMENT ON COLUMN "ESSAYS"."FILE_NAME" IS 'Όνομα αρχείου';
   COMMENT ON COLUMN "ESSAYS"."MIME_TYPE" IS 'Τύπος αρχείου';
   COMMENT ON COLUMN "ESSAYS"."FILE_DATE" IS 'Ημ/νία καταχώρησης';
   COMMENT ON COLUMN "ESSAYS"."CREATED" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "ESSAYS"."CREATED_BY" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "ESSAYS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "ESSAYS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "ESSAYS"."USER_ID" IS 'Επιβλέπων καθηγητής';
   COMMENT ON COLUMN "ESSAYS"."YEAR" IS 'Έτος Εργασίας';
   COMMENT ON COLUMN "ESSAYS"."MONTH" IS 'Μήνας εργασίας';
   COMMENT ON TABLE "ESSAYS"  IS 'Πίνακας Θεμάτων Πτυχιακών Εργασιών';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ESSAYS" 
before
insert or update or delete on "ESSAYS"
for each row
begin
IF INSERTING THEN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_ESSAYS.NEXTVAL INTO :NEW.ID  FROM DUAL;
    END IF;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID'); 
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_ESSAYS" ENABLE;

   COMMENT ON COLUMN "USERS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USERS"."NAME" IS 'Όνομα Χρήστη';
   COMMENT ON COLUMN "USERS"."SURNAME" IS 'Επώνυμο Χρήστη';
   COMMENT ON COLUMN "USERS"."AM" IS 'Αριθμός Μητρώου';
   COMMENT ON COLUMN "USERS"."ROLE_ID" IS 'Ρόλος Χρήστη';
   COMMENT ON COLUMN "USERS"."TYPE_ID" IS 'Κατάσταση Χρήστη';
   COMMENT ON COLUMN "USERS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USERS"."CREATED_BY" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "USERS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USERS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "USERS"."ACTIVE" IS 'Ενεργός Χρήστης: 1 Ανενεργός Χρήστης: 0';
   COMMENT ON TABLE "USERS"  IS 'Διαχειριστής Συστήματος';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USR" 
before insert or update on "USERS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.ID;
    :NEW.ISADMIN := 'USER_ROLE:0';  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USR" ENABLE;

   COMMENT ON COLUMN "USER_CONVERSATIONS"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."TITLE" IS 'Τίτλος Συζήτησης';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."SEND_FROM" IS 'Αποστολέας';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."SEND_TO" IS 'Παραλήπτης';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."IS_CLOSED" IS 'Εχει κλείσει(1: ΝΑΙ, 0: ΟΧΙ)';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_CONV" 
before insert or update on user_conversations
for each row
begin
if inserting then
    if :new.id is null then
        select seq_user_conv.nextval into :new.id from dual;
    end if;
    :new.created := sysdate;
    :new.created_by := v('USER_ID');
    :new.is_Closed := 0;
elsif updating then
    :new.updated := sysdate;
    :new.updated_by := v('USER_ID');
end if;
end;
/
ALTER TRIGGER "TRG_USER_CONV" ENABLE;

  ALTER TABLE "USER_CREDENTIALS" ADD CONSTRAINT "USER_CREDS" FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("ID") ENABLE;

   COMMENT ON COLUMN "USER_CREDENTIALS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USER_CREDENTIALS"."USERNAME" IS 'Ονομα Χρήστη';
   COMMENT ON COLUMN "USER_CREDENTIALS"."PASSWORD" IS 'Κωδικός Χρήστη';
   COMMENT ON COLUMN "USER_CREDENTIALS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_CREDENTIALS"."CREATED_BY" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "USER_CREDENTIALS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_CREDENTIALS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "USER_CREDENTIALS"."USER_ID" IS 'Ξένο κλειδί στον πίνακα USERS';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_CREDS" 
before insert or update on "USER_CREDENTIALS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr_creds.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.USER_ID;  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USER_CREDS" ENABLE;

  ALTER TABLE "USER_DETAILS" ADD CONSTRAINT "USER_DETAILS_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("ID") ENABLE;

   COMMENT ON COLUMN "USER_DETAILS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USER_DETAILS"."EMAIL" IS 'Ηλεκτρονική Διεύθυνση';
   COMMENT ON COLUMN "USER_DETAILS"."PHONE" IS 'Τηλέφωνο';
   COMMENT ON COLUMN "USER_DETAILS"."ADDRESS" IS 'Διεύθυνση';
   COMMENT ON COLUMN "USER_DETAILS"."USER_ID" IS 'ID Χρήστη';
   COMMENT ON COLUMN "USER_DETAILS"."UNIVERSITY_ID" IS 'ID Πανεπιστημίου';
   COMMENT ON COLUMN "USER_DETAILS"."DEPARTMENT_ID" IS 'ID Τμήματος';
   COMMENT ON COLUMN "USER_DETAILS"."STUDY_YEAR" IS 'Έτος Φοίτησης';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_DETAILS" 
before insert or update on "USER_DETAILS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr_details.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.USER_ID;  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USER_DETAILS" ENABLE;

  ALTER TABLE "USER_MESSAGES" ADD CONSTRAINT "USER_MESSAGES_CON" FOREIGN KEY ("CONV_ID")
	  REFERENCES "USER_CONVERSATIONS" ("ID") ENABLE;

   COMMENT ON COLUMN "USER_MESSAGES"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "USER_MESSAGES"."CONV_ID" IS 'Αναγνωριστικό Συνομιλίας';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_TO" IS 'Παραλήπτης';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_FROM" IS 'Αποστολέας';
   COMMENT ON COLUMN "USER_MESSAGES"."IS_READ" IS 'Εχει Διαβαστεί (1: ΝΑΙ, 0: ΟΧΙ)';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_DATE" IS 'Ημερομηνία Αποστολής';
   COMMENT ON COLUMN "USER_MESSAGES"."TEXT" IS 'Κείμενο Μηνύματος';
   COMMENT ON COLUMN "USER_MESSAGES"."FILE_NAME" IS 'Όνομα αρχείου';
   COMMENT ON COLUMN "USER_MESSAGES"."MIME_TYPE" IS 'Τύπος αρχείου';
   COMMENT ON COLUMN "USER_MESSAGES"."FILE_BLOB" IS 'Αρχείο αναλυτικής περιγραφής';
   COMMENT ON COLUMN "USER_MESSAGES"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_MESSAGES"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "USER_MESSAGES"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_MESSAGES"."UPDATED_BY" IS 'Ενημερώθηκε Από';
   COMMENT ON TABLE "USER_MESSAGES"  IS 'Μηνύματα Χρηστών';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_MESS" 
before insert or update on user_messages
for each row
begin
if inserting then
    if :new.id is null then
        select seq_user_mess.nextval into :new.id from dual;
    end if;
    :new.send_date := sysdate;
    :new.is_Read := 0;
    :new.created := sysdate;
    :new.created_by := v('USER_ID');
elsif updating then
    :new.updated := sysdate;
    :new.updated_by := v('USER_ID');
end if;
end;
/
ALTER TRIGGER "TRG_USER_MESS" ENABLE;

   COMMENT ON COLUMN "VERIFICATION_CODE"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "VERIFICATION_CODE"."EMAIL" IS 'Ηλεκτρονική Διεύθυνση';
   COMMENT ON COLUMN "VERIFICATION_CODE"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "VERIFICATION_CODE"."CREATED" IS 'Δημιουργήθηκε';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CODE" 
before
insert or update on "VERIFICATION_CODE"
for each row
begin
    if :new.id is null then
        select seq_code.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
end;
/
ALTER TRIGGER "TRG_CODE" ENABLE;
create or replace function auth_user_credentials(p_username IN VARCHAR2, p_password IN VARCHAR2)
  return boolean
is
  l_count number;
begin
  select count(id)
    into l_count
    from user_credentials
   where upper(username) = upper(p_username)
     and password = p_password;

  if l_count = 1 then
    return true;
  else
    return false;
  end if;

exception
  when others then
    return false;
end;
/
create or replace FUNCTION f_check_char
(
    p_value IN VARCHAR2,
    p_type  IN NUMBER
)
RETURN NUMBER
IS
    v_str VARCHAR2(4000);
BEGIN
    v_str := TRIM(p_value);

    -------------------------------------------------------------------
    -- 102 = NAME (Greek + English letters only + space + . - )
    -------------------------------------------------------------------
    IF p_type = 102 and v_str is not null  THEN

        v_str := UPPER(v_str);

        -- Normalize Greek accents
        v_str := REPLACE(v_str, 'Ά','Α');
        v_str := REPLACE(v_str, 'Έ','Ε');
        v_str := REPLACE(v_str, 'Ή','Η');
        v_str := REPLACE(v_str, 'Ί','Ι');
        v_str := REPLACE(v_str, 'Ό','Ο');
        v_str := REPLACE(v_str, 'Ύ','Υ');
        v_str := REPLACE(v_str, 'Ώ','Ω');
        v_str := REPLACE(v_str, 'Ϊ','Ι');
        v_str := REPLACE(v_str, 'Ϋ','Υ');

        IF NOT REGEXP_LIKE(v_str, '^[A-ZΑ-Ω .-]+$') THEN
            RETURN 1;
        END IF;

    -------------------------------------------------------------------
    -- 103 = PHONE (numbers only)
    -------------------------------------------------------------------
    ELSIF p_type = 103 and v_str is not null THEN

        IF NOT REGEXP_LIKE(v_str, '^[0-9]+$') THEN
            RETURN 1;
        END IF;
    -------------------------------------------------------------------
    -- 104 = EMAIL
    -------------------------------------------------------------------
    ELSIF p_type = 104 and v_str is not null  THEN
    IF NOT REGEXP_LIKE(v_str,
       '^[A-Za-z0-9._%+-]+@(go\.uop\.gr|uop\.gr|GO\.UOP\.GR|UOP\.GR)$')
    THEN
        RETURN 1;
    END IF;

    ELSIF p_type = 105 and v_str is not null THEN
        IF LENGTH(v_str) <= 5 THEN
            RETURN 1;
    END IF;
    -------------------------------------------------------------------
    -- UNKNOWN TYPE
    -------------------------------------------------------------------
    ELSE
        RETURN 0;
    END IF;

    RETURN 0; -- VALID

END f_check_char;
/
create or replace FUNCTION            "F_CLV_DESCR"
  (eucode VARCHAR2) RETURN VARCHAR2 IS

--------------------------------------------------------------------------------------------------
-- Η ΣΥΝΑΡΤΗΣΗ ΕΠΙΣΤΡΕΦΕΙ ΤΗΝ ΠΕΡΙΓΡΑΦΗ ΤΙΜΗΣ ΚΩΔΙΚΟΛΟΓΙΟΥ ΜΕ ΒΑΣΗ ΤΟΝ ΕΝΩΠΟΙΗΜΕΝΟ ΚΩΔΙΚΟ ΤΙΜΗΣ --
--------------------------------------------------------------------------------------------------
  vresult    VARCHAR2(2000 CHAR);
BEGIN
    SELECT description INTO vresult FROM code_list_values WHERE ucode = eucode;   
    RETURN vresult;
END F_CLV_DESCR;
/
create or replace FUNCTION f_get_messages (p_conv_id NUMBER, p_user number)
RETURN NUMBER
IS
    l_count NUMBER;
BEGIN
----
  SELECT COUNT(id)
    INTO l_count
    FROM user_messages
   WHERE conv_id = p_conv_id
     AND is_Read = 0
     AND send_to = p_user;

  RETURN l_count;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;
/
create or replace FUNCTION          "F_PARTIES_ELEMENTS"
  (userID NUMBER,
   celt      NUMBER) RETURN VARCHAR2 IS

  ------------------------------------------------------------------------------
  -- Η ΣΥΝΑΡΤΗΣΗ ΕΠΙΣΤΡΕΦΕΙ ΣΤΟΙΧΕΙΑ ΑΠΟ ΤΟΥΣ ΣΥΝΑΛΛΑΣΣΟΜΕΝΟΥΣ,               --
  ------------------------------------------------------------------------------
  /*
      Τιμές για celt :   101         Ονομασία Συναλλασσομένου
                         102         Σχολή και Τμήμα Συναλλασσομένου
                         103         Στοιχεία Επικοινωνίας(Email και Τηλέφωνο)
                         104         Δικαίωμα Διαχειριστή
                         105         Κατάσταση Χρήστη
                         106         Τύπος Χρήστη(Καθηγητής ή Φοιτητής)
                         107         Ονομασία Συναλλασσομένου + Τύπος(Καθηγητής, Φοιτητής κλπ)
   */

   vresult         VARCHAR2(4000 CHAR);
   begin
        IF celt = 101 THEN 
            SELECT name||' '||surname
            INTO vresult
            FROM users
            WHERE id = userID;
        elsif celt = 102 THEN 
            select f_clv_descr(university_id)||' ('||f_clv_descr(department_id)||')'
            INTO vresult
            FROM user_details 
            WHERE user_id = userID;
        elsif celt = 103 THEN 
            select case when phone is not null then 
                    email||' - ('||phone||')'
                    else
                        email
                    end as info
            INTO vresult
            FROM user_details
            WHERE user_id = userID;
        elsif celt = 104 THEN 
            SELECT isAdmin
            INTO vresult
            FROM users
            WHERE id = userID;
        elsif celt = 105 THEN 
            SELECT active
            INTO vresult
            FROM users
            WHERE id = userID;
        elsif celt = 106 THEN 
            SELECT decode(role_id, 'ROLE:1', 'stud', 'ROLE:2', 'prof')
            INTO vresult
            FROM users
            WHERE id = userID;
        elsif celt = 107 THEN 
            SELECT name||' '||surname||' ('||f_clv_descr(type_id)||')'
            INTO vresult
            FROM users
            WHERE id = userID;
        end if;
        return vresult;
        exception when others then
            vresult := null;        
   end;
/












































  CREATE UNIQUE INDEX "CODE_LIST_VALUES_UNIQUE" ON "CODE_LIST_VALUES" ("UCODE") 
  ;

  CREATE UNIQUE INDEX "ESSAYS_PK" ON "ESSAYS" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00189201993" ON "CODE_LIST" ("CODE") 
  ;

  CREATE UNIQUE INDEX "SYS_C00189985748" ON "USER_MESSAGES" ("ID") 
  ;

  CREATE UNIQUE INDEX "SYS_C00189985769" ON "USER_CONVERSATIONS" ("ID") 
  ;

  CREATE UNIQUE INDEX "USERS_PK" ON "USERS" ("ID") 
  ;

  CREATE UNIQUE INDEX "USER_CREDENTIALS_PK" ON "USER_CREDENTIALS" ("ID") 
  ;

  CREATE UNIQUE INDEX "USER_CREDENTIALS_UN" ON "USER_CREDENTIALS" ("USERNAME") 
  ;

  CREATE UNIQUE INDEX "USER_DETAILS_PK" ON "USER_DETAILS" ("ID") 
  ;

  CREATE UNIQUE INDEX "USER_DETAILS_UN" ON "USER_DETAILS" ("EMAIL") 
  ;

  CREATE UNIQUE INDEX "VERIFICATION_CODE_PK" ON "VERIFICATION_CODE" ("ID") 
  ;

































































































   CREATE SEQUENCE  "SEQ_CL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_CLV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_CODE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_ESSAYS"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_USER_CONV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_USER_MESS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_USR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_USR_CREDS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "SEQ_USR_DETAILS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;








































create or replace TRIGGER "TRG_CL" 
before
insert or update on "CODE_LIST"
for each row
begin
    IF INSERTING THEN
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID'); 
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
create or replace trigger "TRG_CLV"
before insert or update on "CODE_LIST_VALUES"
for each row
begin
    IF INSERTING THEN
    if :new.id is null then
        select seq_clv.nextval into :new.id from dual;
    end if;
    :new.ucode := :new.cl_code||':'||:new.code;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID');  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
create or replace trigger "TRG_CODE"
before
insert or update on "VERIFICATION_CODE"
for each row
begin
    if :new.id is null then
        select seq_code.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
end;
/
create or replace trigger "TRG_ESSAYS"
before
insert or update or delete on "ESSAYS"
for each row
begin
IF INSERTING THEN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_ESSAYS.NEXTVAL INTO :NEW.ID  FROM DUAL;
    END IF;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID'); 
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
create or replace trigger trg_user_conv
before insert or update on user_conversations
for each row
begin
if inserting then
    if :new.id is null then
        select seq_user_conv.nextval into :new.id from dual;
    end if;
    :new.created := sysdate;
    :new.created_by := v('USER_ID');
    :new.is_Closed := 0;
elsif updating then
    :new.updated := sysdate;
    :new.updated_by := v('USER_ID');
end if;
end;
/
create or replace trigger "TRG_USER_CREDS"
before insert or update on "USER_CREDENTIALS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr_creds.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.USER_ID;  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
create or replace trigger "TRG_USER_DETAILS"
before insert or update on "USER_DETAILS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr_details.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.USER_ID;  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
create or replace trigger trg_user_mess
before insert or update on user_messages
for each row
begin
if inserting then
    if :new.id is null then
        select seq_user_mess.nextval into :new.id from dual;
    end if;
    :new.send_date := sysdate;
    :new.is_Read := 0;
    :new.created := sysdate;
    :new.created_by := v('USER_ID');
elsif updating then
    :new.updated := sysdate;
    :new.updated_by := v('USER_ID');
end if;
end;
/
create or replace trigger "TRG_USR"
before insert or update on "USERS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.ID;
    :NEW.ISADMIN := 'USER_ROLE:0';  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/

   COMMENT ON COLUMN "CODE_LIST"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "CODE_LIST"."DESCRIPTION" IS 'Περιγραφή';
   COMMENT ON COLUMN "CODE_LIST"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "CODE_LIST"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "CODE_LIST"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "CODE_LIST"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CL" 
before
insert or update on "CODE_LIST"
for each row
begin
    IF INSERTING THEN
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID'); 
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_CL" ENABLE;

   COMMENT ON COLUMN "CODE_LIST_VALUES"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CL_CODE" IS 'ID Code List';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UCODE" IS 'Κωδικός Εγγραφής';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."DESCRIPTION" IS 'Περιγραφή';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CLV" 
before insert or update on "CODE_LIST_VALUES"
for each row
begin
    IF INSERTING THEN
    if :new.id is null then
        select seq_clv.nextval into :new.id from dual;
    end if;
    :new.ucode := :new.cl_code||':'||:new.code;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID');  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_CLV" ENABLE;

   COMMENT ON COLUMN "ESSAYS"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "ESSAYS"."TITLE" IS 'Τίτλος πτυχιακής';
   COMMENT ON COLUMN "ESSAYS"."DESCRIPTION" IS 'Περιγραφή θέματος πτυχιακής';
   COMMENT ON COLUMN "ESSAYS"."FILE_BLOB" IS 'Αρχείο αναλυτικής περιγραφής';
   COMMENT ON COLUMN "ESSAYS"."FILE_NAME" IS 'Όνομα αρχείου';
   COMMENT ON COLUMN "ESSAYS"."MIME_TYPE" IS 'Τύπος αρχείου';
   COMMENT ON COLUMN "ESSAYS"."FILE_DATE" IS 'Ημ/νία καταχώρησης';
   COMMENT ON COLUMN "ESSAYS"."CREATED" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "ESSAYS"."CREATED_BY" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "ESSAYS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "ESSAYS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "ESSAYS"."USER_ID" IS 'Επιβλέπων καθηγητής';
   COMMENT ON COLUMN "ESSAYS"."YEAR" IS 'Έτος Εργασίας';
   COMMENT ON COLUMN "ESSAYS"."MONTH" IS 'Μήνας εργασίας';
   COMMENT ON TABLE "ESSAYS"  IS 'Πίνακας Θεμάτων Πτυχιακών Εργασιών';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ESSAYS" 
before
insert or update or delete on "ESSAYS"
for each row
begin
IF INSERTING THEN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_ESSAYS.NEXTVAL INTO :NEW.ID  FROM DUAL;
    END IF;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID'); 
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_ESSAYS" ENABLE;

   COMMENT ON COLUMN "USERS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USERS"."NAME" IS 'Όνομα Χρήστη';
   COMMENT ON COLUMN "USERS"."SURNAME" IS 'Επώνυμο Χρήστη';
   COMMENT ON COLUMN "USERS"."AM" IS 'Αριθμός Μητρώου';
   COMMENT ON COLUMN "USERS"."ROLE_ID" IS 'Ρόλος Χρήστη';
   COMMENT ON COLUMN "USERS"."TYPE_ID" IS 'Κατάσταση Χρήστη';
   COMMENT ON COLUMN "USERS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USERS"."CREATED_BY" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "USERS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USERS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "USERS"."ACTIVE" IS 'Ενεργός Χρήστης: 1 Ανενεργός Χρήστης: 0';
   COMMENT ON TABLE "USERS"  IS 'Διαχειριστής Συστήματος';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USR" 
before insert or update on "USERS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.ID;
    :NEW.ISADMIN := 'USER_ROLE:0';  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USR" ENABLE;

   COMMENT ON COLUMN "USER_CONVERSATIONS"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."TITLE" IS 'Τίτλος Συζήτησης';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."SEND_FROM" IS 'Αποστολέας';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."SEND_TO" IS 'Παραλήπτης';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."IS_CLOSED" IS 'Εχει κλείσει(1: ΝΑΙ, 0: ΟΧΙ)';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_CONV" 
before insert or update on user_conversations
for each row
begin
if inserting then
    if :new.id is null then
        select seq_user_conv.nextval into :new.id from dual;
    end if;
    :new.created := sysdate;
    :new.created_by := v('USER_ID');
    :new.is_Closed := 0;
elsif updating then
    :new.updated := sysdate;
    :new.updated_by := v('USER_ID');
end if;
end;
/
ALTER TRIGGER "TRG_USER_CONV" ENABLE;

   COMMENT ON COLUMN "USER_CREDENTIALS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USER_CREDENTIALS"."USERNAME" IS 'Ονομα Χρήστη';
   COMMENT ON COLUMN "USER_CREDENTIALS"."PASSWORD" IS 'Κωδικός Χρήστη';
   COMMENT ON COLUMN "USER_CREDENTIALS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_CREDENTIALS"."CREATED_BY" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "USER_CREDENTIALS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_CREDENTIALS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "USER_CREDENTIALS"."USER_ID" IS 'Ξένο κλειδί στον πίνακα USERS';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_CREDS" 
before insert or update on "USER_CREDENTIALS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr_creds.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.USER_ID;  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USER_CREDS" ENABLE;

   COMMENT ON COLUMN "USER_DETAILS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USER_DETAILS"."EMAIL" IS 'Ηλεκτρονική Διεύθυνση';
   COMMENT ON COLUMN "USER_DETAILS"."PHONE" IS 'Τηλέφωνο';
   COMMENT ON COLUMN "USER_DETAILS"."ADDRESS" IS 'Διεύθυνση';
   COMMENT ON COLUMN "USER_DETAILS"."USER_ID" IS 'ID Χρήστη';
   COMMENT ON COLUMN "USER_DETAILS"."UNIVERSITY_ID" IS 'ID Πανεπιστημίου';
   COMMENT ON COLUMN "USER_DETAILS"."DEPARTMENT_ID" IS 'ID Τμήματος';
   COMMENT ON COLUMN "USER_DETAILS"."STUDY_YEAR" IS 'Έτος Φοίτησης';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_DETAILS" 
before insert or update on "USER_DETAILS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr_details.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.USER_ID;  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USER_DETAILS" ENABLE;

   COMMENT ON COLUMN "USER_MESSAGES"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "USER_MESSAGES"."CONV_ID" IS 'Αναγνωριστικό Συνομιλίας';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_TO" IS 'Παραλήπτης';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_FROM" IS 'Αποστολέας';
   COMMENT ON COLUMN "USER_MESSAGES"."IS_READ" IS 'Εχει Διαβαστεί (1: ΝΑΙ, 0: ΟΧΙ)';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_DATE" IS 'Ημερομηνία Αποστολής';
   COMMENT ON COLUMN "USER_MESSAGES"."TEXT" IS 'Κείμενο Μηνύματος';
   COMMENT ON COLUMN "USER_MESSAGES"."FILE_NAME" IS 'Όνομα αρχείου';
   COMMENT ON COLUMN "USER_MESSAGES"."MIME_TYPE" IS 'Τύπος αρχείου';
   COMMENT ON COLUMN "USER_MESSAGES"."FILE_BLOB" IS 'Αρχείο αναλυτικής περιγραφής';
   COMMENT ON COLUMN "USER_MESSAGES"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_MESSAGES"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "USER_MESSAGES"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_MESSAGES"."UPDATED_BY" IS 'Ενημερώθηκε Από';
   COMMENT ON TABLE "USER_MESSAGES"  IS 'Μηνύματα Χρηστών';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_MESS" 
before insert or update on user_messages
for each row
begin
if inserting then
    if :new.id is null then
        select seq_user_mess.nextval into :new.id from dual;
    end if;
    :new.send_date := sysdate;
    :new.is_Read := 0;
    :new.created := sysdate;
    :new.created_by := v('USER_ID');
elsif updating then
    :new.updated := sysdate;
    :new.updated_by := v('USER_ID');
end if;
end;
/
ALTER TRIGGER "TRG_USER_MESS" ENABLE;

   COMMENT ON COLUMN "VERIFICATION_CODE"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "VERIFICATION_CODE"."EMAIL" IS 'Ηλεκτρονική Διεύθυνση';
   COMMENT ON COLUMN "VERIFICATION_CODE"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "VERIFICATION_CODE"."CREATED" IS 'Δημιουργήθηκε';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CODE" 
before
insert or update on "VERIFICATION_CODE"
for each row
begin
    if :new.id is null then
        select seq_code.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
end;
/
ALTER TRIGGER "TRG_CODE" ENABLE;


















































  CREATE UNIQUE INDEX "SYS_C00189201993" ON "CODE_LIST" ("CODE") 
  ;

   COMMENT ON COLUMN "CODE_LIST"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "CODE_LIST"."DESCRIPTION" IS 'Περιγραφή';
   COMMENT ON COLUMN "CODE_LIST"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "CODE_LIST"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "CODE_LIST"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "CODE_LIST"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CL" 
before
insert or update on "CODE_LIST"
for each row
begin
    IF INSERTING THEN
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID'); 
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_CL" ENABLE;

  CREATE UNIQUE INDEX "CODE_LIST_VALUES_UNIQUE" ON "CODE_LIST_VALUES" ("UCODE") 
  ;

   COMMENT ON COLUMN "CODE_LIST_VALUES"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CL_CODE" IS 'ID Code List';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UCODE" IS 'Κωδικός Εγγραφής';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."DESCRIPTION" IS 'Περιγραφή';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "CODE_LIST_VALUES"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CLV" 
before insert or update on "CODE_LIST_VALUES"
for each row
begin
    IF INSERTING THEN
    if :new.id is null then
        select seq_clv.nextval into :new.id from dual;
    end if;
    :new.ucode := :new.cl_code||':'||:new.code;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID');  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_CLV" ENABLE;

  CREATE UNIQUE INDEX "ESSAYS_PK" ON "ESSAYS" ("ID") 
  ;
  CREATE UNIQUE INDEX "SYS_IL0465651157C00004$$" ON "ESSAYS" (
  ;

   COMMENT ON COLUMN "ESSAYS"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "ESSAYS"."TITLE" IS 'Τίτλος πτυχιακής';
   COMMENT ON COLUMN "ESSAYS"."DESCRIPTION" IS 'Περιγραφή θέματος πτυχιακής';
   COMMENT ON COLUMN "ESSAYS"."FILE_BLOB" IS 'Αρχείο αναλυτικής περιγραφής';
   COMMENT ON COLUMN "ESSAYS"."FILE_NAME" IS 'Όνομα αρχείου';
   COMMENT ON COLUMN "ESSAYS"."MIME_TYPE" IS 'Τύπος αρχείου';
   COMMENT ON COLUMN "ESSAYS"."FILE_DATE" IS 'Ημ/νία καταχώρησης';
   COMMENT ON COLUMN "ESSAYS"."CREATED" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "ESSAYS"."CREATED_BY" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "ESSAYS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "ESSAYS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "ESSAYS"."USER_ID" IS 'Επιβλέπων καθηγητής';
   COMMENT ON COLUMN "ESSAYS"."YEAR" IS 'Έτος Εργασίας';
   COMMENT ON COLUMN "ESSAYS"."MONTH" IS 'Μήνας εργασίας';
   COMMENT ON TABLE "ESSAYS"  IS 'Πίνακας Θεμάτων Πτυχιακών Εργασιών';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ESSAYS" 
before
insert or update or delete on "ESSAYS"
for each row
begin
IF INSERTING THEN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_ESSAYS.NEXTVAL INTO :NEW.ID  FROM DUAL;
    END IF;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := v('USER_ID'); 
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_ESSAYS" ENABLE;

  CREATE UNIQUE INDEX "USERS_PK" ON "USERS" ("ID") 
  ;

   COMMENT ON COLUMN "USERS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USERS"."NAME" IS 'Όνομα Χρήστη';
   COMMENT ON COLUMN "USERS"."SURNAME" IS 'Επώνυμο Χρήστη';
   COMMENT ON COLUMN "USERS"."AM" IS 'Αριθμός Μητρώου';
   COMMENT ON COLUMN "USERS"."ROLE_ID" IS 'Ρόλος Χρήστη';
   COMMENT ON COLUMN "USERS"."TYPE_ID" IS 'Κατάσταση Χρήστη';
   COMMENT ON COLUMN "USERS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USERS"."CREATED_BY" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "USERS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USERS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "USERS"."ACTIVE" IS 'Ενεργός Χρήστης: 1 Ανενεργός Χρήστης: 0';
   COMMENT ON TABLE "USERS"  IS 'Διαχειριστής Συστήματος';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USR" 
before insert or update on "USERS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.ID;
    :NEW.ISADMIN := 'USER_ROLE:0';  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USR" ENABLE;

  CREATE UNIQUE INDEX "SYS_C00189985769" ON "USER_CONVERSATIONS" ("ID") 
  ;

   COMMENT ON COLUMN "USER_CONVERSATIONS"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."TITLE" IS 'Τίτλος Συζήτησης';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."SEND_FROM" IS 'Αποστολέας';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."SEND_TO" IS 'Παραλήπτης';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."IS_CLOSED" IS 'Εχει κλείσει(1: ΝΑΙ, 0: ΟΧΙ)';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_CONVERSATIONS"."UPDATED_BY" IS 'Ενημερώθηκε Από';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_CONV" 
before insert or update on user_conversations
for each row
begin
if inserting then
    if :new.id is null then
        select seq_user_conv.nextval into :new.id from dual;
    end if;
    :new.created := sysdate;
    :new.created_by := v('USER_ID');
    :new.is_Closed := 0;
elsif updating then
    :new.updated := sysdate;
    :new.updated_by := v('USER_ID');
end if;
end;
/
ALTER TRIGGER "TRG_USER_CONV" ENABLE;

  CREATE UNIQUE INDEX "USER_CREDENTIALS_PK" ON "USER_CREDENTIALS" ("ID") 
  ;
  CREATE UNIQUE INDEX "USER_CREDENTIALS_UN" ON "USER_CREDENTIALS" ("USERNAME") 
  ;

   COMMENT ON COLUMN "USER_CREDENTIALS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USER_CREDENTIALS"."USERNAME" IS 'Ονομα Χρήστη';
   COMMENT ON COLUMN "USER_CREDENTIALS"."PASSWORD" IS 'Κωδικός Χρήστη';
   COMMENT ON COLUMN "USER_CREDENTIALS"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_CREDENTIALS"."CREATED_BY" IS 'Δημιουργήθηκε από';
   COMMENT ON COLUMN "USER_CREDENTIALS"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_CREDENTIALS"."UPDATED_BY" IS 'Ενημερώθηκε από';
   COMMENT ON COLUMN "USER_CREDENTIALS"."USER_ID" IS 'Ξένο κλειδί στον πίνακα USERS';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_CREDS" 
before insert or update on "USER_CREDENTIALS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr_creds.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.USER_ID;  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USER_CREDS" ENABLE;

  CREATE UNIQUE INDEX "USER_DETAILS_PK" ON "USER_DETAILS" ("ID") 
  ;
  CREATE UNIQUE INDEX "USER_DETAILS_UN" ON "USER_DETAILS" ("EMAIL") 
  ;

   COMMENT ON COLUMN "USER_DETAILS"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "USER_DETAILS"."EMAIL" IS 'Ηλεκτρονική Διεύθυνση';
   COMMENT ON COLUMN "USER_DETAILS"."PHONE" IS 'Τηλέφωνο';
   COMMENT ON COLUMN "USER_DETAILS"."ADDRESS" IS 'Διεύθυνση';
   COMMENT ON COLUMN "USER_DETAILS"."USER_ID" IS 'ID Χρήστη';
   COMMENT ON COLUMN "USER_DETAILS"."UNIVERSITY_ID" IS 'ID Πανεπιστημίου';
   COMMENT ON COLUMN "USER_DETAILS"."DEPARTMENT_ID" IS 'ID Τμήματος';
   COMMENT ON COLUMN "USER_DETAILS"."STUDY_YEAR" IS 'Έτος Φοίτησης';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_DETAILS" 
before insert or update on "USER_DETAILS"
for each row
begin
IF INSERTING THEN
    if :new.id is null then
        select seq_usr_details.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
    :NEW.CREATED_BY := :NEW.USER_ID;  
ELSIF UPDATING THEN
    :NEW.UPDATED := sysdate;
    :NEW.UPDATED_BY := v('USER_ID');
END IF;
end;
/
ALTER TRIGGER "TRG_USER_DETAILS" ENABLE;

  CREATE UNIQUE INDEX "SYS_C00189985748" ON "USER_MESSAGES" ("ID") 
  ;
  CREATE UNIQUE INDEX "SYS_IL0467121192C00010$$" ON "USER_MESSAGES" (
  ;

   COMMENT ON COLUMN "USER_MESSAGES"."ID" IS 'Μοναδικό αναγνωριστικό';
   COMMENT ON COLUMN "USER_MESSAGES"."CONV_ID" IS 'Αναγνωριστικό Συνομιλίας';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_TO" IS 'Παραλήπτης';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_FROM" IS 'Αποστολέας';
   COMMENT ON COLUMN "USER_MESSAGES"."IS_READ" IS 'Εχει Διαβαστεί (1: ΝΑΙ, 0: ΟΧΙ)';
   COMMENT ON COLUMN "USER_MESSAGES"."SEND_DATE" IS 'Ημερομηνία Αποστολής';
   COMMENT ON COLUMN "USER_MESSAGES"."TEXT" IS 'Κείμενο Μηνύματος';
   COMMENT ON COLUMN "USER_MESSAGES"."FILE_NAME" IS 'Όνομα αρχείου';
   COMMENT ON COLUMN "USER_MESSAGES"."MIME_TYPE" IS 'Τύπος αρχείου';
   COMMENT ON COLUMN "USER_MESSAGES"."FILE_BLOB" IS 'Αρχείο αναλυτικής περιγραφής';
   COMMENT ON COLUMN "USER_MESSAGES"."CREATED" IS 'Δημιουργήθηκε';
   COMMENT ON COLUMN "USER_MESSAGES"."CREATED_BY" IS 'Δημιουργήθηκε Από';
   COMMENT ON COLUMN "USER_MESSAGES"."UPDATED" IS 'Ενημερώθηκε';
   COMMENT ON COLUMN "USER_MESSAGES"."UPDATED_BY" IS 'Ενημερώθηκε Από';
   COMMENT ON TABLE "USER_MESSAGES"  IS 'Μηνύματα Χρηστών';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_USER_MESS" 
before insert or update on user_messages
for each row
begin
if inserting then
    if :new.id is null then
        select seq_user_mess.nextval into :new.id from dual;
    end if;
    :new.send_date := sysdate;
    :new.is_Read := 0;
    :new.created := sysdate;
    :new.created_by := v('USER_ID');
elsif updating then
    :new.updated := sysdate;
    :new.updated_by := v('USER_ID');
end if;
end;
/
ALTER TRIGGER "TRG_USER_MESS" ENABLE;

  CREATE UNIQUE INDEX "VERIFICATION_CODE_PK" ON "VERIFICATION_CODE" ("ID") 
  ;

   COMMENT ON COLUMN "VERIFICATION_CODE"."ID" IS 'Μοναδικό Αναγνωριστικό';
   COMMENT ON COLUMN "VERIFICATION_CODE"."EMAIL" IS 'Ηλεκτρονική Διεύθυνση';
   COMMENT ON COLUMN "VERIFICATION_CODE"."CODE" IS 'Κωδικός';
   COMMENT ON COLUMN "VERIFICATION_CODE"."CREATED" IS 'Δημιουργήθηκε';

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_CODE" 
before
insert or update on "VERIFICATION_CODE"
for each row
begin
    if :new.id is null then
        select seq_code.nextval into :new.id from dual;
    end if;
    :NEW.CREATED := sysdate;
end;
/
ALTER TRIGGER "TRG_CODE" ENABLE;































































































